<?php

/**
 * Created by PhpStorm.
 * User: irelance
 * Date: 2017/9/30
 * Time: 上午10:05
 */
namespace Irelance\Mozjs34;
if (php_sapi_name() == 'cli') {
    define('CLIENT_EOL', PHP_EOL);
} else {
    define('CLIENT_EOL', "<br>");
}

define('JSID_TYPE_STRING', 0x0);
define('JSID_TYPE_INT', 0x1);
define('JSID_TYPE_VOID', 0x2);
define('JSID_TYPE_SYMBOL', 0x4);
define('JSID_TYPE_MASK', 0x7);

define("js_undefined_str", "undefined");
define("js_typeof_str", "typeof");
define("js_void_str", "void");
define("js_null_str", "null");
define("js_false_str", "false");
define("js_true_str", "true");
define("js_throw_str", "throw");
define("js_in_str", "in");
define("js_instanceof_str", "instanceof");
define("js_this_str", "this");
define("js_new_str", "new");

class Constant
{
    const _ConstTag = [
        'SCRIPT_INT',
        'SCRIPT_DOUBLE',
        'SCRIPT_ATOM',
        'SCRIPT_TRUE',
        'SCRIPT_FALSE',
        'SCRIPT_NULL',
        'SCRIPT_OBJECT',
        'SCRIPT_VOID',
        'SCRIPT_HOLE',
    ];

    const _Class = [
        'CK_BlockObject',
        'CK_WithObject',
        'CK_JSFunction',
        'CK_JSObject'
    ];

    const _ScriptBits = [
        'NoScriptRval',
        'SavedCallerFun',
        'Strict',
        'ContainsDynamicNameAccess',
        'FunHasExtensibleScope',
        'FunNeedsDeclEnvObject',
        'FunHasAnyAliasedFormal',
        'ArgumentsHasVarBinding',
        'NeedsArgsObj',
        'IsGeneratorExp',
        'IsLegacyGenerator',
        'IsStarGenerator',
        'OwnSource',
        'ExplicitUseStrict',
        'SelfHosted',
        'IsCompileAndGo',
        'HasSingleton',
        'TreatAsRunOnce',
        'HasLazyScript'
    ];

    const _FirstWordFlag = [
        'HasAtom' => 0x1,
        'IsStarGenerator' => 0x2,
        'IsLazy' => 0x4,
        'HasSingletonType' => 0x8
    ];

    const _Opcode = [
        0 => ['op' => 'JSOP_NOP', 'val' => 0, 'name' => "nop", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        1 => ['op' => 'JSOP_UNDEFINED', 'val' => 1, 'name' => js_undefined_str, 'image' => "", 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        2 => ['op' => 'JSOP_UNUSED2', 'val' => 2, 'name' => "unused2", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ['JOF_BYTE']],
        3 => ['op' => 'JSOP_ENTERWITH', 'val' => 3, 'name' => "enterwith", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 0, 'format' => ['JOF_OBJECT']],
        4 => ['op' => 'JSOP_LEAVEWITH', 'val' => 4, 'name' => "leavewith", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        5 => ['op' => 'JSOP_RETURN', 'val' => 5, 'name' => "return", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ['JOF_BYTE']],
        6 => ['op' => 'JSOP_GOTO', 'val' => 6, 'name' => "goto", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ['JOF_JUMP']],
        7 => ['op' => 'JSOP_IFEQ', 'val' => 7, 'name' => "ifeq", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 0, 'format' => ['JOF_JUMP', 'JOF_DETECTING']],
        8 => ['op' => 'JSOP_IFNE', 'val' => 8, 'name' => "ifne", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 0, 'format' => ['JOF_JUMP']],
        9 => ['op' => 'JSOP_ARGUMENTS', 'val' => 9, 'name' => "arguments", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        10 => ['op' => 'JSOP_SWAP', 'val' => 10, 'name' => "swap", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 2, 'format' => ['JOF_BYTE']],
        11 => ['op' => 'JSOP_POPN', 'val' => 11, 'name' => "popn", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 0, 'format' => ['JOF_UINT16']],
        12 => ['op' => 'JSOP_DUP', 'val' => 12, 'name' => "dup", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 2, 'format' => ['JOF_BYTE']],
        13 => ['op' => 'JSOP_DUP2', 'val' => 13, 'name' => "dup2", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 4, 'format' => ['JOF_BYTE']],
        14 => ['op' => 'JSOP_SETCONST', 'val' => 14, 'name' => "setconst", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_SET']],
        15 => ['op' => 'JSOP_BITOR', 'val' => 15, 'name' => "bitor", 'image' => "|", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        16 => ['op' => 'JSOP_BITXOR', 'val' => 16, 'name' => "bitxor", 'image' => "^", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        17 => ['op' => 'JSOP_BITAND', 'val' => 17, 'name' => "bitand", 'image' => "&", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        18 => ['op' => 'JSOP_EQ', 'val' => 18, 'name' => "eq", 'image' => "==", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH', 'JOF_DETECTING']],
        19 => ['op' => 'JSOP_NE', 'val' => 19, 'name' => "ne", 'image' => "!=", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH', 'JOF_DETECTING']],
        20 => ['op' => 'JSOP_LT', 'val' => 20, 'name' => "lt", 'image' => "<", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        21 => ['op' => 'JSOP_LE', 'val' => 21, 'name' => "le", 'image' => "<=", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        22 => ['op' => 'JSOP_GT', 'val' => 22, 'name' => "gt", 'image' => ">", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        23 => ['op' => 'JSOP_GE', 'val' => 23, 'name' => "ge", 'image' => ">=", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        24 => ['op' => 'JSOP_LSH', 'val' => 24, 'name' => "lsh", 'image' => "<<", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        25 => ['op' => 'JSOP_RSH', 'val' => 25, 'name' => "rsh", 'image' => ">>", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        26 => ['op' => 'JSOP_URSH', 'val' => 26, 'name' => "ursh", 'image' => ">>>", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        27 => ['op' => 'JSOP_ADD', 'val' => 27, 'name' => "add", 'image' => "+", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        28 => ['op' => 'JSOP_SUB', 'val' => 28, 'name' => "sub", 'image' => "-", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        29 => ['op' => 'JSOP_MUL', 'val' => 29, 'name' => "mul", 'image' => "*", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        30 => ['op' => 'JSOP_DIV', 'val' => 30, 'name' => "div", 'image' => "/", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        31 => ['op' => 'JSOP_MOD', 'val' => 31, 'name' => "mod", 'image' => "%", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        32 => ['op' => 'JSOP_NOT', 'val' => 32, 'name' => "not", 'image' => "!", 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ARITH', 'JOF_DETECTING']],
        33 => ['op' => 'JSOP_BITNOT', 'val' => 33, 'name' => "bitnot", 'image' => "~", 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ARITH']],
        34 => ['op' => 'JSOP_NEG', 'val' => 34, 'name' => "neg", 'image' => "- ", 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ARITH']],
        35 => ['op' => 'JSOP_POS', 'val' => 35, 'name' => "pos", 'image' => "+ ", 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ARITH']],
        36 => ['op' => 'JSOP_DELNAME', 'val' => 36, 'name' => "delname", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME']],
        37 => ['op' => 'JSOP_DELPROP', 'val' => 37, 'name' => "delprop", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_PROP']],
        38 => ['op' => 'JSOP_DELELEM', 'val' => 38, 'name' => "delelem", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ELEM']],
        39 => ['op' => 'JSOP_TYPEOF', 'val' => 39, 'name' => js_typeof_str, 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_DETECTING']],
        40 => ['op' => 'JSOP_VOID', 'val' => 40, 'name' => js_void_str, 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE']],
        41 => ['op' => 'JSOP_SPREADCALL', 'val' => 41, 'name' => "spreadcall", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_INVOKE', 'JOF_TYPESET']],
        42 => ['op' => 'JSOP_SPREADNEW', 'val' => 42, 'name' => "spreadnew", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_INVOKE', 'JOF_TYPESET']],
        43 => ['op' => 'JSOP_SPREADEVAL', 'val' => 43, 'name' => "spreadeval", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_INVOKE', 'JOF_TYPESET']],
        44 => ['op' => 'JSOP_DUPAT', 'val' => 44, 'name' => "dupat", 'image' => NULL, 'len' => 4, 'use' => 0, 'def' => 1, 'format' => ['JOF_UINT24']],
        45 => ['op' => 'JSOP_UNUSED45', 'val' => 45, 'name' => "unused45", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        46 => ['op' => 'JSOP_UNUSED46', 'val' => 46, 'name' => "unused46", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        47 => ['op' => 'JSOP_UNUSED47', 'val' => 47, 'name' => "unused47", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        48 => ['op' => 'JSOP_UNUSED48', 'val' => 48, 'name' => "unused48", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        49 => ['op' => 'JSOP_UNUSED49', 'val' => 49, 'name' => "unused49", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        50 => ['op' => 'JSOP_UNUSED50', 'val' => 50, 'name' => "unused50", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        51 => ['op' => 'JSOP_UNUSED51', 'val' => 51, 'name' => "unused51", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        52 => ['op' => 'JSOP_UNUSED52', 'val' => 52, 'name' => "unused52", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        53 => ['op' => 'JSOP_GETPROP', 'val' => 53, 'name' => "getprop", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_PROP', 'JOF_TYPESET', 'JOF_TMPSLOT3']],
        54 => ['op' => 'JSOP_SETPROP', 'val' => 54, 'name' => "setprop", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_PROP', 'JOF_SET', 'JOF_DETECTING']],
        55 => ['op' => 'JSOP_GETELEM', 'val' => 55, 'name' => "getelem", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ELEM', 'JOF_TYPESET', 'JOF_LEFTASSOC']],
        56 => ['op' => 'JSOP_SETELEM', 'val' => 56, 'name' => "setelem", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ELEM', 'JOF_SET', 'JOF_DETECTING']],
        57 => ['op' => 'JSOP_UNUSED57', 'val' => 57, 'name' => "unused57", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        58 => ['op' => 'JSOP_CALL', 'val' => 58, 'name' => "call", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ['JOF_UINT16', 'JOF_INVOKE', 'JOF_TYPESET']],
        59 => ['op' => 'JSOP_NAME', 'val' => 59, 'name' => "name", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_TYPESET']],
        60 => ['op' => 'JSOP_DOUBLE', 'val' => 60, 'name' => "double", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_DOUBLE']],
        61 => ['op' => 'JSOP_STRING', 'val' => 61, 'name' => "string", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_ATOM']],
        62 => ['op' => 'JSOP_ZERO', 'val' => 62, 'name' => "zero", 'image' => "0", 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        63 => ['op' => 'JSOP_ONE', 'val' => 63, 'name' => "one", 'image' => "1", 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        64 => ['op' => 'JSOP_NULL', 'val' => 64, 'name' => js_null_str, 'image' => js_null_str, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        65 => ['op' => 'JSOP_THIS', 'val' => 65, 'name' => js_this_str, 'image' => js_this_str, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        66 => ['op' => 'JSOP_FALSE', 'val' => 66, 'name' => js_false_str, 'image' => js_false_str, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        67 => ['op' => 'JSOP_TRUE', 'val' => 67, 'name' => js_true_str, 'image' => js_true_str, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        68 => ['op' => 'JSOP_OR', 'val' => 68, 'name' => "or", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_JUMP', 'JOF_DETECTING', 'JOF_LEFTASSOC']],
        69 => ['op' => 'JSOP_AND', 'val' => 69, 'name' => "and", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_JUMP', 'JOF_DETECTING', 'JOF_LEFTASSOC']],
        70 => ['op' => 'JSOP_TABLESWITCH', 'val' => 70, 'name' => "tableswitch", 'image' => NULL, 'len' => -1, 'use' => 1, 'def' => 0, 'format' => ['JOF_TABLESWITCH', 'JOF_DETECTING']],
        71 => ['op' => 'JSOP_RUNONCE', 'val' => 71, 'name' => "runonce", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        72 => ['op' => 'JSOP_STRICTEQ', 'val' => 72, 'name' => "stricteq", 'image' => "===", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_DETECTING', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        73 => ['op' => 'JSOP_STRICTNE', 'val' => 73, 'name' => "strictne", 'image' => "!==", 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_DETECTING', 'JOF_LEFTASSOC', 'JOF_ARITH']],
        74 => ['op' => 'JSOP_SETCALL', 'val' => 74, 'name' => "setcall", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        75 => ['op' => 'JSOP_ITER', 'val' => 75, 'name' => "iter", 'image' => NULL, 'len' => 2, 'use' => 1, 'def' => 1, 'format' => ['JOF_UINT8']],
        76 => ['op' => 'JSOP_MOREITER', 'val' => 76, 'name' => "moreiter", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 2, 'format' => ['JOF_BYTE']],
        77 => ['op' => 'JSOP_ITERNEXT', 'val' => 77, 'name' => "iternext", 'image' => "<next>", 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        78 => ['op' => 'JSOP_ENDITER', 'val' => 78, 'name' => "enditer", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ['JOF_BYTE']],
        79 => ['op' => 'JSOP_FUNAPPLY', 'val' => 79, 'name' => "funapply", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ['JOF_UINT16', 'JOF_INVOKE', 'JOF_TYPESET']],
        80 => ['op' => 'JSOP_OBJECT', 'val' => 80, 'name' => "object", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_OBJECT']],
        81 => ['op' => 'JSOP_POP', 'val' => 81, 'name' => "pop", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ['JOF_BYTE']],
        82 => ['op' => 'JSOP_NEW', 'val' => 82, 'name' => js_new_str, 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ['JOF_UINT16', 'JOF_INVOKE', 'JOF_TYPESET']],
        83 => ['op' => 'JSOP_UNUSED83', 'val' => 83, 'name' => "unused83", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        84 => ['op' => 'JSOP_GETARG', 'val' => 84, 'name' => "getarg", 'image' => NULL, 'len' => 3, 'use' => 0, 'def' => 1, 'format' => ['JOF_QARG', 'JOF_NAME']],
        85 => ['op' => 'JSOP_SETARG', 'val' => 85, 'name' => "setarg", 'image' => NULL, 'len' => 3, 'use' => 1, 'def' => 1, 'format' => ['JOF_QARG', 'JOF_NAME', 'JOF_SET']],
        86 => ['op' => 'JSOP_GETLOCAL', 'val' => 86, 'name' => "getlocal", 'image' => NULL, 'len' => 4, 'use' => 0, 'def' => 1, 'format' => ['JOF_LOCAL', 'JOF_NAME']],
        87 => ['op' => 'JSOP_SETLOCAL', 'val' => 87, 'name' => "setlocal", 'image' => NULL, 'len' => 4, 'use' => 1, 'def' => 1, 'format' => ['JOF_LOCAL', 'JOF_NAME', 'JOF_SET', 'JOF_DETECTING']],
        88 => ['op' => 'JSOP_UINT16', 'val' => 88, 'name' => "uint16", 'image' => NULL, 'len' => 3, 'use' => 0, 'def' => 1, 'format' => ['JOF_UINT16']],
        89 => ['op' => 'JSOP_NEWINIT', 'val' => 89, 'name' => "newinit", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_UINT8']],
        90 => ['op' => 'JSOP_NEWARRAY', 'val' => 90, 'name' => "newarray", 'image' => NULL, 'len' => 4, 'use' => 0, 'def' => 1, 'format' => ['JOF_UINT24']],
        91 => ['op' => 'JSOP_NEWOBJECT', 'val' => 91, 'name' => "newobject", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_OBJECT']],
        92 => ['op' => 'JSOP_ENDINIT', 'val' => 92, 'name' => "endinit", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        93 => ['op' => 'JSOP_INITPROP', 'val' => 93, 'name' => "initprop", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_PROP', 'JOF_SET', 'JOF_DETECTING']],
        94 => ['op' => 'JSOP_INITELEM', 'val' => 94, 'name' => "initelem", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ELEM', 'JOF_SET', 'JOF_DETECTING']],
        95 => ['op' => 'JSOP_INITELEM_INC', 'val' => 95, 'name' => "initelem_inc", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 2, 'format' => ['JOF_BYTE', 'JOF_ELEM', 'JOF_SET']],
        96 => ['op' => 'JSOP_INITELEM_ARRAY', 'val' => 96, 'name' => "initelem_array", 'image' => NULL, 'len' => 4, 'use' => 2, 'def' => 1, 'format' => ['JOF_UINT24', 'JOF_ELEM', 'JOF_SET', 'JOF_DETECTING']],
        97 => ['op' => 'JSOP_INITPROP_GETTER', 'val' => 97, 'name' => "initprop_getter", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_PROP', 'JOF_SET', 'JOF_DETECTING']],
        98 => ['op' => 'JSOP_INITPROP_SETTER', 'val' => 98, 'name' => "initprop_setter", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_PROP', 'JOF_SET', 'JOF_DETECTING']],
        99 => ['op' => 'JSOP_INITELEM_GETTER', 'val' => 99, 'name' => "initelem_getter", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ELEM', 'JOF_SET', 'JOF_DETECTING']],
        100 => ['op' => 'JSOP_INITELEM_SETTER', 'val' => 100, 'name' => "initelem_setter", 'image' => NULL, 'len' => 1, 'use' => 3, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ELEM', 'JOF_SET', 'JOF_DETECTING']],
        101 => ['op' => 'JSOP_CALLSITEOBJ', 'val' => 101, 'name' => "callsiteobj", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_OBJECT']],
        102 => ['op' => 'JSOP_NEWARRAY_COPYONWRITE', 'val' => 102, 'name' => "newarray_copyonwrite", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_OBJECT']],
        103 => ['op' => 'JSOP_UNUSED103', 'val' => 103, 'name' => "unused103", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        104 => ['op' => 'JSOP_UNUSED104', 'val' => 104, 'name' => "unused104", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        105 => ['op' => 'JSOP_UNUSED105', 'val' => 105, 'name' => "unused105", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        106 => ['op' => 'JSOP_LABEL', 'val' => 106, 'name' => "label", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ['JOF_JUMP']],
        107 => ['op' => 'JSOP_UNUSED107', 'val' => 107, 'name' => "unused107", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        108 => ['op' => 'JSOP_FUNCALL', 'val' => 108, 'name' => "funcall", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ['JOF_UINT16', 'JOF_INVOKE', 'JOF_TYPESET']],
        109 => ['op' => 'JSOP_LOOPHEAD', 'val' => 109, 'name' => "loophead", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        110 => ['op' => 'JSOP_BINDNAME', 'val' => 110, 'name' => "bindname", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_SET']],
        111 => ['op' => 'JSOP_SETNAME', 'val' => 111, 'name' => "setname", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_SET', 'JOF_DETECTING']],
        112 => ['op' => 'JSOP_THROW', 'val' => 112, 'name' => js_throw_str, 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ['JOF_BYTE']],
        113 => ['op' => 'JSOP_IN', 'val' => 113, 'name' => js_in_str, 'image' => js_in_str, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC']],
        114 => ['op' => 'JSOP_INSTANCEOF', 'val' => 114, 'name' => js_instanceof_str, 'image' => js_instanceof_str, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_LEFTASSOC', 'JOF_TMPSLOT']],
        115 => ['op' => 'JSOP_DEBUGGER', 'val' => 115, 'name' => "debugger", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        116 => ['op' => 'JSOP_GOSUB', 'val' => 116, 'name' => "gosub", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ['JOF_JUMP']],
        117 => ['op' => 'JSOP_RETSUB', 'val' => 117, 'name' => "retsub", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 0, 'format' => ['JOF_BYTE']],
        118 => ['op' => 'JSOP_EXCEPTION', 'val' => 118, 'name' => "exception", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        119 => ['op' => 'JSOP_LINENO', 'val' => 119, 'name' => "lineno", 'image' => NULL, 'len' => 3, 'use' => 0, 'def' => 0, 'format' => ['JOF_UINT16']],
        120 => ['op' => 'JSOP_CONDSWITCH', 'val' => 120, 'name' => "condswitch", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        121 => ['op' => 'JSOP_CASE', 'val' => 121, 'name' => "case", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ['JOF_JUMP']],
        122 => ['op' => 'JSOP_DEFAULT', 'val' => 122, 'name' => "default", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 0, 'format' => ['JOF_JUMP']],
        123 => ['op' => 'JSOP_EVAL', 'val' => 123, 'name' => "eval", 'image' => NULL, 'len' => 3, 'use' => -1, 'def' => 1, 'format' => ['JOF_UINT16', 'JOF_INVOKE', 'JOF_TYPESET']],
        124 => ['op' => 'JSOP_UNUSED124', 'val' => 124, 'name' => "unused124", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        125 => ['op' => 'JSOP_UNUSED125', 'val' => 125, 'name' => "unused125", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        126 => ['op' => 'JSOP_UNUSED126', 'val' => 126, 'name' => "unused126", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        127 => ['op' => 'JSOP_DEFFUN', 'val' => 127, 'name' => "deffun", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ['JOF_OBJECT']],
        128 => ['op' => 'JSOP_DEFCONST', 'val' => 128, 'name' => "defconst", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ['JOF_ATOM']],
        129 => ['op' => 'JSOP_DEFVAR', 'val' => 129, 'name' => "defvar", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ['JOF_ATOM']],
        130 => ['op' => 'JSOP_LAMBDA', 'val' => 130, 'name' => "lambda", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_OBJECT']],
        131 => ['op' => 'JSOP_LAMBDA_ARROW', 'val' => 131, 'name' => "lambda_arrow", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_OBJECT']],
        132 => ['op' => 'JSOP_CALLEE', 'val' => 132, 'name' => "callee", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        133 => ['op' => 'JSOP_PICK', 'val' => 133, 'name' => "pick", 'image' => NULL, 'len' => 2, 'use' => 0, 'def' => 0, 'format' => ['JOF_UINT8', 'JOF_TMPSLOT2']],
        134 => ['op' => 'JSOP_TRY', 'val' => 134, 'name' => "try", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        135 => ['op' => 'JSOP_FINALLY', 'val' => 135, 'name' => "finally", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 2, 'format' => ['JOF_BYTE']],
        136 => ['op' => 'JSOP_GETALIASEDVAR', 'val' => 136, 'name' => "getaliasedvar", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_SCOPECOORD', 'JOF_NAME', 'JOF_TYPESET']],
        137 => ['op' => 'JSOP_SETALIASEDVAR', 'val' => 137, 'name' => "setaliasedvar", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_SCOPECOORD', 'JOF_NAME', 'JOF_SET', 'JOF_DETECTING']],
        138 => ['op' => 'JSOP_UNUSED138', 'val' => 138, 'name' => "unused138", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        139 => ['op' => 'JSOP_UNUSED139', 'val' => 139, 'name' => "unused139", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        140 => ['op' => 'JSOP_UNUSED140', 'val' => 140, 'name' => "unused140", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        141 => ['op' => 'JSOP_UNUSED141', 'val' => 141, 'name' => "unused141", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        142 => ['op' => 'JSOP_UNUSED142', 'val' => 142, 'name' => "unused142", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        143 => ['op' => 'JSOP_GETINTRINSIC', 'val' => 143, 'name' => "getintrinsic", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_TYPESET']],
        144 => ['op' => 'JSOP_SETINTRINSIC', 'val' => 144, 'name' => "setintrinsic", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_SET', 'JOF_DETECTING']],
        145 => ['op' => 'JSOP_BINDINTRINSIC', 'val' => 145, 'name' => "bindintrinsic", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_SET']],
        146 => ['op' => 'JSOP_UNUSED146', 'val' => 146, 'name' => "unused146", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        147 => ['op' => 'JSOP_UNUSED147', 'val' => 147, 'name' => "unused147", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        148 => ['op' => 'JSOP_UNUSED148', 'val' => 148, 'name' => "unused148", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        149 => ['op' => 'JSOP_BACKPATCH', 'val' => 149, 'name' => "backpatch", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ['JOF_JUMP']],
        150 => ['op' => 'JSOP_UNUSED150', 'val' => 150, 'name' => "unused150", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        151 => ['op' => 'JSOP_THROWING', 'val' => 151, 'name' => "throwing", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ['JOF_BYTE']],
        152 => ['op' => 'JSOP_SETRVAL', 'val' => 152, 'name' => "setrval", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 0, 'format' => ['JOF_BYTE']],
        153 => ['op' => 'JSOP_RETRVAL', 'val' => 153, 'name' => "retrval", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        154 => ['op' => 'JSOP_GETGNAME', 'val' => 154, 'name' => "getgname", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_TYPESET', 'JOF_GNAME']],
        155 => ['op' => 'JSOP_SETGNAME', 'val' => 155, 'name' => "setgname", 'image' => NULL, 'len' => 5, 'use' => 2, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_SET', 'JOF_DETECTING', 'JOF_GNAME']],
        156 => ['op' => 'JSOP_UNUSED156', 'val' => 156, 'name' => "unused156", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        157 => ['op' => 'JSOP_UNUSED157', 'val' => 157, 'name' => "unused157", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        158 => ['op' => 'JSOP_UNUSED158', 'val' => 158, 'name' => "unused158", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        159 => ['op' => 'JSOP_UNUSED159', 'val' => 159, 'name' => "unused159", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        160 => ['op' => 'JSOP_REGEXP', 'val' => 160, 'name' => "regexp", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_REGEXP']],
        161 => ['op' => 'JSOP_UNUSED161', 'val' => 161, 'name' => "unused161", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        162 => ['op' => 'JSOP_UNUSED162', 'val' => 162, 'name' => "unused162", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        163 => ['op' => 'JSOP_UNUSED163', 'val' => 163, 'name' => "unused163", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        164 => ['op' => 'JSOP_UNUSED164', 'val' => 164, 'name' => "unused164", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        165 => ['op' => 'JSOP_UNUSED165', 'val' => 165, 'name' => "unused165", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        166 => ['op' => 'JSOP_UNUSED166', 'val' => 166, 'name' => "unused166", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        167 => ['op' => 'JSOP_UNUSED167', 'val' => 167, 'name' => "unused167", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        168 => ['op' => 'JSOP_UNUSED168', 'val' => 168, 'name' => "unused168", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        169 => ['op' => 'JSOP_UNUSED169', 'val' => 169, 'name' => "unused169", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        170 => ['op' => 'JSOP_UNUSED170', 'val' => 170, 'name' => "unused170", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        171 => ['op' => 'JSOP_UNUSED171', 'val' => 171, 'name' => "unused171", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        172 => ['op' => 'JSOP_UNUSED172', 'val' => 172, 'name' => "unused172", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        173 => ['op' => 'JSOP_UNUSED173', 'val' => 173, 'name' => "unused173", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        174 => ['op' => 'JSOP_UNUSED174', 'val' => 174, 'name' => "unused174", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        175 => ['op' => 'JSOP_UNUSED175', 'val' => 175, 'name' => "unused175", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        176 => ['op' => 'JSOP_UNUSED176', 'val' => 176, 'name' => "unused176", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        177 => ['op' => 'JSOP_UNUSED177', 'val' => 177, 'name' => "unused177", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        178 => ['op' => 'JSOP_UNUSED178', 'val' => 178, 'name' => "unused178", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        179 => ['op' => 'JSOP_UNUSED179', 'val' => 179, 'name' => "unused179", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        180 => ['op' => 'JSOP_UNUSED180', 'val' => 180, 'name' => "unused180", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        181 => ['op' => 'JSOP_UNUSED181', 'val' => 181, 'name' => "unused181", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        182 => ['op' => 'JSOP_UNUSED182', 'val' => 182, 'name' => "unused182", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        183 => ['op' => 'JSOP_UNUSED183', 'val' => 183, 'name' => "unused183", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        184 => ['op' => 'JSOP_CALLPROP', 'val' => 184, 'name' => "callprop", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_PROP', 'JOF_TYPESET', 'JOF_TMPSLOT3']],
        185 => ['op' => 'JSOP_UNUSED185', 'val' => 185, 'name' => "unused185", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        186 => ['op' => 'JSOP_UNUSED186', 'val' => 186, 'name' => "unused186", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        187 => ['op' => 'JSOP_UNUSED187', 'val' => 187, 'name' => "unused187", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        188 => ['op' => 'JSOP_UINT24', 'val' => 188, 'name' => "uint24", 'image' => NULL, 'len' => 4, 'use' => 0, 'def' => 1, 'format' => ['JOF_UINT24']],
        189 => ['op' => 'JSOP_UNUSED189', 'val' => 189, 'name' => "unused189", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        190 => ['op' => 'JSOP_UNUSED190', 'val' => 190, 'name' => "unused190", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        191 => ['op' => 'JSOP_UNUSED191', 'val' => 191, 'name' => "unused191", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        192 => ['op' => 'JSOP_UNUSED192', 'val' => 192, 'name' => "unused192", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        193 => ['op' => 'JSOP_CALLELEM', 'val' => 193, 'name' => "callelem", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_ELEM', 'JOF_TYPESET', 'JOF_LEFTASSOC']],
        194 => ['op' => 'JSOP_MUTATEPROTO', 'val' => 194, 'name' => "mutateproto", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 1, 'format' => ['JOF_BYTE']],
        195 => ['op' => 'JSOP_GETXPROP', 'val' => 195, 'name' => "getxprop", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_PROP', 'JOF_TYPESET']],
        196 => ['op' => 'JSOP_UNUSED196', 'val' => 196, 'name' => "unused196", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        197 => ['op' => 'JSOP_TYPEOFEXPR', 'val' => 197, 'name' => "typeofexpr", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_DETECTING']],
        198 => ['op' => 'JSOP_PUSHBLOCKSCOPE', 'val' => 198, 'name' => "pushblockscope", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 0, 'format' => ['JOF_OBJECT']],
        199 => ['op' => 'JSOP_POPBLOCKSCOPE', 'val' => 199, 'name' => "popblockscope", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        200 => ['op' => 'JSOP_DEBUGLEAVEBLOCK', 'val' => 200, 'name' => "debugleaveblock", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        201 => ['op' => 'JSOP_UNUSED201', 'val' => 201, 'name' => "unused201", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        202 => ['op' => 'JSOP_GENERATOR', 'val' => 202, 'name' => "generator", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        203 => ['op' => 'JSOP_YIELD', 'val' => 203, 'name' => "yield", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE']],
        204 => ['op' => 'JSOP_ARRAYPUSH', 'val' => 204, 'name' => "arraypush", 'image' => NULL, 'len' => 1, 'use' => 2, 'def' => 0, 'format' => ['JOF_BYTE']],
        205 => ['op' => 'JSOP_UNUSED205', 'val' => 205, 'name' => "unused205", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        206 => ['op' => 'JSOP_UNUSED206', 'val' => 206, 'name' => "unused206", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        207 => ['op' => 'JSOP_UNUSED207', 'val' => 207, 'name' => "unused207", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        208 => ['op' => 'JSOP_UNUSED208', 'val' => 208, 'name' => "unused208", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        209 => ['op' => 'JSOP_UNUSED209', 'val' => 209, 'name' => "unused209", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        210 => ['op' => 'JSOP_UNUSED210', 'val' => 210, 'name' => "unused210", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        211 => ['op' => 'JSOP_UNUSED211', 'val' => 211, 'name' => "unused211", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        212 => ['op' => 'JSOP_UNUSED212', 'val' => 212, 'name' => "unused212", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        213 => ['op' => 'JSOP_UNUSED213', 'val' => 213, 'name' => "unused213", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        214 => ['op' => 'JSOP_BINDGNAME', 'val' => 214, 'name' => "bindgname", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_NAME', 'JOF_SET', 'JOF_GNAME']],
        215 => ['op' => 'JSOP_INT8', 'val' => 215, 'name' => "int8", 'image' => NULL, 'len' => 2, 'use' => 0, 'def' => 1, 'format' => ['JOF_INT8']],
        216 => ['op' => 'JSOP_INT32', 'val' => 216, 'name' => "int32", 'image' => NULL, 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_INT32']],
        217 => ['op' => 'JSOP_LENGTH', 'val' => 217, 'name' => "length", 'image' => NULL, 'len' => 5, 'use' => 1, 'def' => 1, 'format' => ['JOF_ATOM', 'JOF_PROP', 'JOF_TYPESET', 'JOF_TMPSLOT3']],
        218 => ['op' => 'JSOP_HOLE', 'val' => 218, 'name' => "hole", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE']],
        219 => ['op' => 'JSOP_UNUSED219', 'val' => 219, 'name' => "unused219", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        220 => ['op' => 'JSOP_UNUSED220', 'val' => 220, 'name' => "unused220", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        221 => ['op' => 'JSOP_UNUSED221', 'val' => 221, 'name' => "unused221", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        222 => ['op' => 'JSOP_UNUSED222', 'val' => 222, 'name' => "unused222", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        223 => ['op' => 'JSOP_UNUSED223', 'val' => 223, 'name' => "unused223", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 0, 'format' => ['JOF_BYTE']],
        224 => ['op' => 'JSOP_REST', 'val' => 224, 'name' => "rest", 'image' => NULL, 'len' => 1, 'use' => 0, 'def' => 1, 'format' => ['JOF_BYTE', 'JOF_TYPESET']],
        225 => ['op' => 'JSOP_TOID', 'val' => 225, 'name' => "toid", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE']],
        226 => ['op' => 'JSOP_IMPLICITTHIS', 'val' => 226, 'name' => "implicitthis", 'image' => "", 'len' => 5, 'use' => 0, 'def' => 1, 'format' => ['JOF_ATOM']],
        227 => ['op' => 'JSOP_LOOPENTRY', 'val' => 227, 'name' => "loopentry", 'image' => NULL, 'len' => 2, 'use' => 0, 'def' => 0, 'format' => ['JOF_UINT8']],
        228 => ['op' => 'JSOP_TOSTRING', 'val' => 228, 'name' => "tostring", 'image' => NULL, 'len' => 1, 'use' => 1, 'def' => 1, 'format' => ['JOF_BYTE']],
    ];
}
